spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/literaryworld
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=15
refresh-token.expiration-days=30